site_name: LemonTree Documentation
theme: readthedocs
docs_dir: docs
repo_url: http://github.com/khshim/LemonTree
site_url: http://lemontree.readthedocs.io/

pages:
    - Home: index.md
    - Utils:
        - Data Utils: utils/data_utils.md
        - Graph Utils: utils/graph_utils.md
        - Parameter Utils: utils/param_utils.md
        - Type Utils: utils/type_utils.md